Repository insightsengineering/rtables, pull requests merged in 2022-11, with the labels that each got.

#433 390 str warning@main
  NAMESPACE
  R/summary.R
  R/tt_showmethods.R
  man/int_methods.Rd
Labels: enhancement, fast fix

#439 Fix typo
  R/tt_toString.R
  man/table_shell.Rd
  man/tostring.Rd
Labels: documentation, fast fix

#402 Correcting typos.
  R/colby_constructors.R
  man/analyze.Rd
  man/spl_context.Rd
Labels: documentation

#440 Review Vignettes
  vignettes/baseline.Rmd
  vignettes/clinical_trials.Rmd
  vignettes/sorting_pruning.Rmd
Labels: enhancement, documentation

#438 Add function links in vignettes
  vignettes/baseline.Rmd
  vignettes/clinical_trials.Rmd
  vignettes/introduction.Rmd
  vignettes/manual_table_construction.Rmd
  vignettes/sorting_pruning.Rmd
  vignettes/subsetting_tables.Rmd
  vignettes/tabulation_concepts.Rmd
  vignettes/tabulation_dplyr.Rmd
  vignettes/title_footer.Rmd
Labels: enhancement, documentation

#432 431 document align@main
  R/argument_conventions.R
  R/tt_afun_utils.R
  R/utils.R
  _pkgdown.yml
  man/CellValue.Rd
  man/in_rows.Rd
  man/lyt_args.Rd
  man/rcell.Rd
  man/rtables_aligns.Rd
  vignettes/custom_appearance.Rmd
  vignettes/introduction.Rmd
  vignettes/manual_table_construction.Rmd
  vignettes/sorting_pruning.Rmd
  vignettes/subsetting_tables.Rmd
  vignettes/tabulation_dplyr.Rmd
Labels: documentation

#468 priority - fixing tests
  tests/testthat/test-printing.R
Labels: bug, priority, automation

#457 tests for cell and label wrapping
  R/tt_export.R
  tests/testthat/setup-fakedata.R
  tests/testthat/test-exporters.R
  tests/testthat/test-pagination.R
  tests/testthat/test-printing.R
Labels: automation
