Repository insightsengineering/rtables, pull requests merged in 2023-01, with the labels that each got.

#484 Ensure spl_context has row for root state with full data. #483
  R/colby_constructors.R
  R/tt_dotabulation.R
  R/utils.R
  man/analyze.Rd
  man/analyze_colvars.Rd
  man/spl_context.Rd
  man/split_rows_by.Rd
  man/summarize_row_groups.Rd
  tests/testthat/test-lyt-tabulation.R
Labels: enhancement, warning

#495 Add wrapping to custom appearance vignette
  vignettes/custom_appearance.Rmd
Labels: documentation

#503 Add example custom spl fnc
  R/split_funs.R
  man/custom_split_funs.Rd
  man/split_cols_by.Rd
  man/split_funcs.Rd
  man/split_rows_by.Rd
Labels: enhancement, documentation
