Repository insightsengineering/rtables, pull requests merged in 2023-09, with the labels that each got.

#693 Adds min package version
  .github/workflows/scheduled.yaml
  DESCRIPTION
  NEWS.md
Labels: core

#719 Prototypes for docx
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/tt_export.R
  man/export_as_docx.Rd
  man/tt_to_flextable.Rd
  tests/testthat/test-exporters.R
Labels: enhancement, exploration, sme

#739 Fix bug causing all-`NA` rows to be included in all `.df_row` splits
  NEWS.md
  R/split_funs.R
  tests/testthat/test-lyt-tabulation.R
Labels: sme
