Repository insightsengineering/rtables, pull requests merged in 2023-08, with the labels that each got.

#700 Fixes to various row_labels situations with tests.
  NAMESPACE
  R/tt_dotabulation.R
  inst/WORDLIST
  man/qtable_layout.Rd
  tests/testthat/test-lyt-tabulation.R
Labels: sme

#665 adding col split names and paths clearly to `.spl_context`
  NEWS.md
  R/colby_constructors.R
  R/make_subset_expr.R
  R/split_funs.R
  R/tt_dotabulation.R
  R/utils.R
  _pkgdown.yml
  man/additional_fun_params.Rd
  man/analyze.Rd
  man/analyze_colvars.Rd
  man/spl_context.Rd
  man/summarize_row_groups.Rd
  tests/testthat/test-lyt-tabulation.R
  tests/testthat/test-tab_afun_cfun.R
  tests/testthat/test_utils.R
Labels: enhancement, sme, epic

#712 Error at table build time when page-by splits generate zero facets.
  NEWS.md
  R/argument_conventions.R
  R/split_funs.R
  inst/WORDLIST
  man/lyt_args.Rd
  man/split_rows_by.Rd
  tests/testthat/test-lyt-tabulation.R
Labels: bug, priority, sme

#718 707 squash bad warning
  NEWS.md
  R/split_funs.R
  tests/testthat/test-lyt-tabulation.R
Labels: sme

#714 Minor docs update for qtable.
  NEWS.md
  R/tt_dotabulation.R
  man/qtable_layout.Rd
Labels: sme

#602 Keep annotations when rbinding two tables
  NEWS.md
  R/tree_accessors.R
  R/tt_compatibility.R
  man/formatters_methods.Rd
  man/rbind.Rd
  tests/testthat/test-binding.R
Labels: sme

#697 Close #695: Add qtable vignette.
  NEWS.md
  _pkgdown.yml
  vignettes/exploratory_analysis.Rmd
Labels: sme

#724 linking main_footer documentation from formatters.
  R/argument_conventions.R
  R/colby_constructors.R
  R/tt_afun_utils.R
  man/basic_table.Rd
  man/constr_args.Rd
  man/in_rows.Rd
  man/qtable_layout.Rd
  man/rowclasses.Rd
  man/tabclasses.Rd
Labels: sme

#725 Organize vignettes, update site template
  _pkgdown.yml
Labels: documentation, sme

#721 Catching errors for mismatches in alt_counts_df splits
  NEWS.md
  R/tt_dotabulation.R
  R/utils.R
  tests/testthat/test-tab_afun_cfun.R
Labels: bug, automation, tests, sme

#726 vbump 0.6.3, [skip vbump]
  DESCRIPTION
  NEWS.md
  vignettes/exploratory_analysis.Rmd
Labels: sme
