Repository insightsengineering/rtables, pull requests merged in 2023-10, with the labels that each got.

#740 [skip vbump] Release v0.6.4
  DESCRIPTION
  NEWS.md
  man/formatters_methods.Rd
Labels: release, sme

#741 Adapting to formatters changes to allow whitespaces
  NEWS.md
  R/tt_paginate.R
  man/paginate.Rd
  man/tostring.Rd
  tests/testthat/test-printing.R
  tests/testthat/test-regressions.R
Labels: bug, enhancement, sme

#742 Fixing Viewer and as_html for \n manual varlabels
  NEWS.md
  R/Viewer.R
  R/as_html.R
  man/as_html.Rd
  tests/testthat/test-exporters.R
Labels: bug, sme

#743 Update read me with training part 2 slides
  README.md
  inst/extdata/Advanced_rtables_part1.pdf
  inst/extdata/Advances_rtables_part2.pdf
Labels: sme

#746 Add tests@208 support for newline@main
  R/tt_export.R
  R/tt_toString.R
  tests/testthat/test-exporters.R
  tests/testthat/test-lyt-tabulation.R
  tests/testthat/test-printing.R
Labels: sme

#751 adding newlines support for footers and titles
  R/tt_toString.R
  tests/testthat/setup-fakedata.R
  tests/testthat/test-printing.R
Labels: bug, sme

#754 Fix integration for version 6.4
  tests/testthat/setup-fakedata.R
  tests/testthat/test-pagination.R
Labels: sme

#756 Update logo
  README.Rmd
  README.md
  man/figures/rtables.png
  man/figures/rtables_logo.svg
  man/figures/rtables_logo_large.png
  man/figures/rtables_logo_small.png
Labels: blocked, sme

#748 update ref_group column ordering
  NEWS.md
  R/tt_dotabulation.R
Labels: sme
