Repository insightsengineering/rtables, pull requests merged in 2023-11, with the labels that each got.

#614 Split Machinery and Tabulation - Dev Guide
  inst/dev-guide/dg_debug_rtables.Rmd
  inst/dev-guide/dg_split_machinery.Rmd
  inst/dev-guide/dg_tabulation.Rmd
  rtables.Rproj
Labels: documentation, sme

#744 Add developer guide to pkgdown site
  .gitignore
  NEWS.md
  _pkgdown.yml
  inst/dev-guide/dg_debug_rtables.html
  inst/dev-guide/dg_split_machinery.html
  inst/dev-guide/dg_tabulation.html
Labels: sme

#770 Add favicon to pkgdown site
  .Rbuildignore
  .gitignore
  README.Rmd
  README.md
  man/figures/logo.png
  pkgdown/favicon/apple-touch-icon-120x120.png
  pkgdown/favicon/apple-touch-icon-152x152.png
  pkgdown/favicon/apple-touch-icon-180x180.png
  pkgdown/favicon/apple-touch-icon-60x60.png
  pkgdown/favicon/apple-touch-icon-76x76.png
  pkgdown/favicon/apple-touch-icon.png
  pkgdown/favicon/favicon-16x16.png
  pkgdown/favicon/favicon-32x32.png
  pkgdown/favicon/favicon.ico
Labels: sme

#772 Fix bug when footnote path contains named elements
  R/index_footnotes.R
Labels: bug, sme

#777 Keep whitespace in html tables
  NEWS.md
  R/as_html.R
  tests/testthat/test-exporters.R
Labels: sme

#780 Align table html output with ASCII output
  NEWS.md
  R/Viewer.R
  R/as_html.R
  man/Viewer.Rd
  man/as_html.Rd
  tests/testthat/test-exporters.R
Labels: sme

#782 761 better getter seeters@221 fix separator div@main
  NAMESPACE
  NEWS.md
  R/00tabletrees.R
  R/argument_conventions.R
  R/colby_constructors.R
  R/tree_accessors.R
  R/tt_dotabulation.R
  R/tt_paginate.R
  R/tt_toString.R
  _pkgdown.yml
  man/avarspl.Rd
  man/basic_table.Rd
  man/constr_args.Rd
  man/rowclasses.Rd
  man/section_div.Rd
  man/tabclasses.Rd
  tests/testthat/test-accessors.R
  tests/testthat/test-printing.R
  vignettes/dev-guide/dg_notes.Rmd
Labels: bug, tests, sme

#789 `hsep` propagation fix
  NEWS.md
  R/argument_conventions.R
  R/tt_toString.R
  man/build_table.Rd
  man/export_as_pdf.Rd
  man/gen_args.Rd
  man/paginate.Rd
  man/rtable.Rd
  man/tabclasses.Rd
  man/table_shell.Rd
  man/tostring.Rd
  man/tt_to_flextable.Rd
  tests/testthat/test-printing.R
Labels: enhancement, sme

#791 Add `na_str` argument to `analyze_colvars`
  NEWS.md
  R/colby_constructors.R
  man/analyze_colvars.Rd
  tests/testthat/test-lyt-tabulation.R
Labels: sme

#793 Direct formatted output from `as_result_df`
  DESCRIPTION
  NEWS.md
  R/tt_export.R
  R/tt_from_df.R
  R/utils.R
  man/as_result_df.Rd
  man/data.frame_export.Rd
  man/df_to_tt.Rd
  man/path_enriched_df.Rd
  man/result_df_specs.Rd
  man/tsv_io.Rd
  tests/testthat/test-result_data_frame.R
Labels: enhancement, sme

#794 Fix potential tt at path issue
  NEWS.md
  R/tt_paginate.R
  R/tt_pos_and_access.R
  tests/testthat/test-subset-access.R
Labels: enhancement, sme
