Repository insightsengineering/rtables, pull requests merged in 2023-02, with the labels that each got.

#511 Adding regression test for indentation and col wrapping
  R/tt_toString.R
  man/matrix_form-VTableTree-method.Rd
  tests/testthat/test-printing.R
Labels: bug, tests

#523 512 Adding example and vignette entry for `split_*_by_cutfun()`
  R/colby_constructors.R
  man/varcuts.Rd
  vignettes/advanced_usage.Rmd
Labels: documentation

#525 513 Add example(s) to `tt_at_path`
  R/tt_pos_and_access.R
  man/ttap.Rd
Labels: documentation

#529 Clean up `rcell` and unused argument documentation
  R/argument_conventions.R
  R/tt_afun_utils.R
  man/CellValue.Rd
  man/compat_args.Rd
  man/rcell.Rd
  man/rheader.Rd
  man/rrow.Rd
  man/rrowl.Rd
  man/rtable.Rd
Labels: documentation

#545 Review vignettes to improve readability
  README.Rmd
  _pkgdown.yml
  vignettes/baseline.Rmd
  vignettes/format_precedence.Rmd
  vignettes/sorting_pruning.Rmd
  vignettes/tabulation_concepts.Rmd
  vignettes/title_footer.Rmd
Labels: documentation, sme

#547 Update grammar and spelling errors.
  vignettes/baseline.Rmd
  vignettes/clinical_trials.Rmd
  vignettes/introduction.Rmd
  vignettes/subsetting_tables.Rmd
  vignettes/tabulation_dplyr.Rmd
Labels: sme

#546 Add examples for pruning
  R/tt_compare_tables.R
  man/prune_table.Rd
  man/trim_prune_funs.Rd
  man/trim_rows.Rd
Labels: sme

#548 reflow text in all vignettes (except sorting)
  vignettes/baseline.Rmd
  vignettes/clinical_trials.Rmd
  vignettes/custom_appearance.Rmd
  vignettes/introduction.Rmd
  vignettes/manual_table_construction.Rmd
  vignettes/subsetting_tables.Rmd
  vignettes/tabulation_concepts.Rmd
  vignettes/title_footer.Rmd
Labels: sme

#550 Additions to sorting vignette
  inst/WORDLIST
  vignettes/sorting_pruning.Rmd
Labels: documentation, sme

#557 Review of split functions vignette
  R/split_funs.R
  man/split_funcs.Rd
  vignettes/split_functions.Rmd
Labels: sme
