Repository insightsengineering/rtables, pull requests merged in 2024-11, with the labels that each got.

#946 split package
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/tt_as_flextable.R
  R/tt_export.R
  _pkgdown.yml
  man/export_as_docx.Rd
  man/tt_to_flextable.Rd
  tests/testthat/test-exporters.R
  tests/testthat/test-tt_as_flextable.R
Labels: sme

#954 Refactor of `as_result_df`
  NAMESPACE
  NEWS.md
  R/tt_as_df.R
  _pkgdown.yml
  man/data.frame_export.Rd
  tests/testthat/test-binding.R
  tests/testthat/test-result_data_frame.R
  vignettes/ard_how_to.Rmd
Labels: sme, ARD

#956 Correct printing output for topleft information
  .github/workflows/docs.yaml
  DESCRIPTION
  tests/testthat/test-printing.R
Labels: bug, sme

#965 fix: fixed an issue of a solitary NA as var_labels passed to analyze
  .revdeprefs.yaml
  NEWS.md
  R/colby_constructors.R
  tests/testthat/test-colby_constructors.R
Labels: sme

#958 Adding stat_names and support for row/col splits and `ContentRow`
  NAMESPACE
  NEWS.md
  R/00tabletrees.R
  R/colby_constructors.R
  R/tree_accessors.R
  R/tt_afun_utils.R
  R/tt_as_df.R
  R/utils.R
  inst/WORDLIST
  man/CellValue.Rd
  man/in_rows.Rd
  man/int_methods.Rd
  man/rcell.Rd
  tests/testthat/test-result_data_frame.R
  vignettes/ard_how_to.Rmd
Labels: enhancement, sme, ARD
