Repository insightsengineering/rtables, pull requests merged in 2024-07, with the labels that each got.

#899 Fix `as_html` newlines and add parameters to `export_as_tsv`
  DESCRIPTION
  NEWS.md
  R/as_html.R
  R/tt_export.R
  README.Rmd
  README.md
  man/as_html.Rd
  man/tsv_io.Rd
  tests/testthat/test-as_html.R
  tests/testthat/test-exporters.R
Labels: bug, enhancement, sme

#900 Update ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE.md
Labels: sme

#905 Reorganize, test, and document useful split functions
  DESCRIPTION
  NEWS.md
  R/custom_split_funs.R
  R/default_split_funs.R
  inst/WORDLIST
  man/add_combo_levels.Rd
  man/add_overall_level.Rd
  man/custom_split_funs.Rd
  man/do_base_split.Rd
  man/split_funcs.Rd
  man/trim_levels_to_map.Rd
  tests/testthat/test-custom_split_funs.R
  tests/testthat/test-default_split_funs.R
  tests/testthat/test-regressions.R
  vignettes/clinical_trials.Rmd
  vignettes/col_counts.Rmd
Labels: bug, enhancement, documentation, sme
