Repository insightsengineering/rtables, pull requests merged in 2024-02, with the labels that each got.

#818 fix `as_result_df` for nested `rbind`
  NEWS.md
  R/tt_export.R
  R/tt_from_df.R
  man/data.frame_export.Rd
  man/df_to_tt.Rd
  tests/testthat/test-result_data_frame.R
Labels: sme

#829 hotfix for `as_result_df` edge case
  NEWS.md
  R/tt_export.R
  tests/testthat/test-result_data_frame.R
Labels: bug, sme

#817 fix sort behavior for root, add useful error, docs and tests
  NEWS.md
  R/tt_sort.R
  man/sort_at_path.Rd
  tests/testthat/test-sort-prune.R
Labels: bug, enhancement, sme

#831 Fix "vals" typo
  R/tt_compatibility.R
Labels: sme
