Repository insightsengineering/rtables, pull requests merged in 2024-01, with the labels that each got.

#811 `value_formats` addition to vignette and docs
  R/tree_accessors.R
  R/tt_toString.R
  man/table_shell.Rd
  man/value_formats.Rd
  vignettes/introspecting_tables.Rmd
Labels: documentation, sme

#807 Design cheatsheet
  .Rbuildignore
  inst/cheatsheet/rtables_cheatsheet_01-24.pdf
  inst/cheatsheet/rtables_cheatsheet_01-24.pptx
Labels: sme

#814 Moved relevant decoration expansion into formatters for rlistings fix
  NEWS.md
  R/tt_toString.R
  tests/testthat/setup-fakedata.R
  tests/testthat/test-exporters.R
  tests/testthat/test-pagination.R
  tests/testthat/test-printing.R
Labels: bug, sme
