Repository insightsengineering/rtables, pull requests merged in 2024-09, with the labels that each got.

#928 update green ci
  DESCRIPTION
  R/colby_constructors.R
  R/default_split_funs.R
  R/summary.R
  R/tree_accessors.R
  R/tt_export.R
  R/tt_pos_and_access.R
  R/tt_toString.R
  man/add_overall_level.Rd
  man/analyze_colvars.Rd
  man/append_topleft.Rd
  man/cell_values.Rd
  man/export_as_docx.Rd
  man/gfc.Rd
  man/int_methods.Rd
  man/matrix_form-VTableTree-method.Rd
  man/row_paths_summary.Rd
  man/split_cols_by.Rd
  man/split_cols_by_multivar.Rd
  man/split_rows_by.Rd
  man/table_shell.Rd
  man/table_structure.Rd
  man/tostring.Rd
  man/tt_to_flextable.Rd
  man/varcuts.Rd
  tests/testthat/setup-fakedata.R
  tests/testthat/test-as_html.R
  tests/testthat/test-exporters.R
  tests/testthat/test-formatting.R
  tests/testthat/test-printing.R
  tests/testthat/test-tab_afun_cfun.R
  vignettes/clinical_trials.Rmd
  vignettes/col_counts.Rmd
  vignettes/custom_appearance.Rmd
  vignettes/example_analysis_coxreg.Rmd
  vignettes/exploratory_analysis.Rmd
  vignettes/introspecting_tables.Rmd
  vignettes/rtables.Rmd
  vignettes/sorting_pruning.Rmd
  vignettes/split_functions.Rmd
  vignettes/subsetting_tables.Rmd
  vignettes/tabulation_concepts.Rmd
  vignettes/tabulation_dplyr.Rmd
  vignettes/title_footer.Rmd
Labels: sme

#923 Workflow propagations
  .github/workflows/check.yaml
  .github/workflows/scheduled.yaml
Labels: automation, sme

#934 Update DESCRIPTION, upversion formatters minimal version to 0.5.9
  DESCRIPTION
Labels: sme

#932 bug fixes and init pagination
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/tt_as_df.R
  R/tt_as_flextable.R
  R/tt_export.R
  man/data.frame_export.Rd
  man/tt_to_flextable.Rd
  rtables.Rproj
  tests/testthat/test-exporters.R
  tests/testthat/test-tt_as_flextable.R
Labels: bug, enhancement, sme

#936 update news and description to 0.6.10, [skip vbump]
  DESCRIPTION
  NEWS.md
Labels: sme
