Repository insightsengineering/rtables, pull requests merged in 2024-08, with the labels that each got.

#911 Dev Guide printing finalization
  NEWS.md
  R/tt_toString.R
  _pkgdown.yml
  vignettes/dev-guide/dg_printing.Rmd
Labels: sme

#917 Merge simple_analysis.R into utils.R
  DESCRIPTION
  NEWS.md
  R/simple_analysis.R
  R/utils.R
  man/rtinner.Rd
Labels: documentation, sme

#912 Fix indentation bugs and a couple of other issues
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/tt_export.R
  man/export_as_docx.Rd
  man/tt_to_flextable.Rd
  tests/testthat/test-exporters.R
Labels: bug, enhancement, sme
