Repository insightsengineering/rtables, pull requests merged in 2025-02, with the labels that each got.

#993 fix #992
  tests/testthat/test-result_data_frame.R
Labels: sme

#989 Remove lookup-refs
  .github/workflows/check.yaml
  .github/workflows/docs.yaml
  .github/workflows/scheduled.yaml
Labels: core

#997 Fix `[<-` formatting bug
  NEWS.md
  R/tt_pos_and_access.R
  man/brackets.Rd
  rtables.Rproj
  tests/testthat/test-subset-access.R
Labels: sme

#996 fix every row sep behavior of analyze section_div
  NEWS.md
  R/colby_constructors.R
  R/tree_accessors.R
  R/tt_dotabulation.R
  inst/WORDLIST
  man/analyze.Rd
  tests/testthat/test-accessors.R
  tests/testthat/test-printing.R
Labels: sme

#994 fix `tt_at_path` and adding test coverage to error in sorting
  NEWS.md
  R/tt_pos_and_access.R
  tests/testthat/test-sort-prune.R
  tests/testthat/test-subset-access.R
Labels: bug, sme
